# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'lib/templates/**/*'
    - 'config/deploy.rb'
    - 'config/deploy/*.rb'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

# UTF-8 is the default encoding in Ruby 2.0
Style/Encoding:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

# 80 characters limit is too strict
Metrics/LineLength:
  Max: 140

# A Hash literal do not wrap spaces({aaa: bbb}), as a difference with a inline block({ ... })
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
